name: SuraxPlugin
main: ch.jalu.surax.SuraxPlugin
version: 1.0
softdepend:
    - Essentials
commands:
    nearhome:
        description: Finds your homes nearest to you
        usage: '/nearhome [-flat]'
    hideme:
        description: Hides a player from the supplied players
        usage: '/hideme <players...>'
    unhideme:
       description: Unhides a player from the supplied players
       usage: '/unhideme <players...>'
    hide:
       description: Hides a player from the given players
       usage: '/hide <hider> <hiddenFrom...>'
    unhide:
       description: Unhides a player from the given players
       usage: '/unhide <hider> <hiddenFrom...>'
    pvp:
       description: Toggles PVP on or off. PVP only works between two players with PVP enabled.
       usage: '/pvp on | /pvp off | /pvp on <player> | /pvp off <player>'
    freeze:
       description: Freezes a player (no movement or commands allowed)
       usage: '/freeze <player>'
    unfreeze:
       description: Unfreeze a player
       usage: '/unfreeze <player>'
    tdeop:
       description: Allows a player to deop himself for a short time
       usage: '/tdeop'
    reop:
       description: Allows a temporarily deopped player to reop himself manually
       usage: '/reop'
    bakeall:
       description: Turns all wheat of the player's inventory into bread
       usage: '/bakeall'
    fixup:
       description: Performs item repair (crafts broken tools together if no durability is lost)
       usage: '/fixall'
permissions:
    surax.nearhome:
         description: Usage of /nearhome to see one's own homes
         default: op
    surax.hideme:
         description: Usage of the /hideme and /unhideme command
         default: op
    surax.hide:
         description: Usage of the /hide command
         default: op
    surax.pvp:
         description: Usage of the /pvp command
         default: op
    surax.pvp.others:
         description: Allows to manipulate other players with /pvp
         default: op
    surax.freeze:
         description: Usage of the /freeze and /unfreeze commands
         default: op
    surax.tdeop:
         description: Gives access to /tdeop and /reop
         default: op
    surax.bakeall:
         description: Gives access to /bakeall
         default: true
    surax.fixup:
         description: Usage of /fixup
         default: true